name = "hugo-org"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["document", "bootstrap"]
features = ["document", ""]
min_version = 0.01

[author]
  name = "coderzh"
  homepage = "https://github.com/coderzh"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
